watchlist: watchlist.json
exchanges:
  bist:
    name: "Borsa İstanbul"
    mic: "XIST"
    timezone: "Europe/Istanbul"
    symbol_suffix: ":BIST"
    markets:
      equities:
        session:
          open: "10:00"
          close: "18:00"
      derivatives:
        session:
          open: "09:30"
          close: "18:15"
  nasdaq:
    name: "Nasdaq"
    mic: "XNAS"
    timezone: "America/New_York"
    symbol_suffix: ""
    markets:
      equities:
        session:
          open: "09:30"
          close: "16:00"
